# Generated by Django 6.0.2 on 2026-02-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sketches/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
